# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RMQ_HOST: rabbitmq
  RMQ_PORT: 5672
  RMQ_USER: guest
  RMQ_PASSWORD: guest
  MARGAY_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/

jobs:
  build:
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Run tests
      run: make test
    - name: Build
      run: make build

